# Generated by Django 4.1.1 on 2022-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('demail', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('appointment_date', models.CharField(max_length=200)),
                ('appointment_time', models.CharField(max_length=200)),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
