# Generated by Django 4.1.1 on 2022-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=50)),
                ('d_email', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(max_length=200)),
                ('appointment_time', models.CharField(choices=[('9am', '9am'), ('10am', '10am'), ('11am', '11am'), ('12am', '12am'), ('5pm', '5pm')], max_length=200)),
                ('payment_status', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=20)),
                ('appointment_status', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('d_email', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
