# Generated by Django 4.1.1 on 2022-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
